version: 2
formats:
  - htmlzip

build:
  os: "ubuntu-22.04"
  tools:
    python: "{{ cookiecutter.python_version }}"

python:
  install:
    - docs/doc_requirements.txt

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
