# This workflow will install Python dependencies, run tests and lint with a single version of Python using nox
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: main
run-name: Lint and Test to code

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        python: ["3.12"]


    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up nox
        uses: wntrblm/nox@main
      - name: Run ruff for code Linting
        run: nox -s lint
      - name: Run pytest for test
        run: |
          nox -s test-cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
